/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.iit.cs445.spring22;

public class TableLamp {
	private Lightbulb myLightbulb;
	private PushdownButton myButton;
	
	public TableLamp() {
		this.myLightbulb = new Lightbulb();
		this.myButton = new PushdownButton(this.myLightbulb);
	}
	
	public TableLamp(Lightbulb lightbulb) {
		this.myLightbulb = lightbulb;
		this.myButton = new PushdownButton(lightbulb);
	}
	
	public void pushButton() {
		this.myButton.pushButton();
	}
}
