/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.iit.cs445.spring22;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.io.ByteArrayOutputStream;
import java.io.OutputStream;
import java.io.PrintStream;

class TableLampTest {
	
	Lightbulb testLight = new Lightbulb();
	Button testButton = new Button(testLight);
	PrintStream old = System.out;
	OutputStream baos = new ByteArrayOutputStream();
	PrintStream ps = new PrintStream(baos);
	
    @Test
    void test_button_direct_switch_on() {
		System.setOut(ps);
		ps.flush();
		testButton.switchOn();
		testButton.switchOn();
		String msg = baos.toString();
		System.setOut(old);
		assertEquals(String.format("Button switched to ON\nButton switched to ON"), msg);
    }
    
    @Test
    void test_button_direct_switch_off() {
		System.setOut(ps);
		ps.flush();
		testButton.switchOff();
		testButton.switchOff();
		String msg = baos.toString();
		System.setOut(old);
		assertEquals(String.format("Button switched to OFF\nButton switched to OFF"), msg);
    }
}
